env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:storybook/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
rules:
  react/react-in-jsx-scope: 0
  react/prop-types: 0
  '@typescript-eslint/no-non-null-assertion': 0
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }]
settings:
  react:
    version: 17.x
